        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 28 17:31:44 2017
        MODULE GEONWAVE_PARA_INITIALIZE__genmod
          INTERFACE 
            SUBROUTINE GEONWAVE_PARA_INITIALIZE
            END SUBROUTINE GEONWAVE_PARA_INITIALIZE
          END INTERFACE 
        END MODULE GEONWAVE_PARA_INITIALIZE__genmod
