        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 28 17:31:44 2017
        MODULE GEONWAVE_INITIALIZE__genmod
          INTERFACE 
            SUBROUTINE GEONWAVE_INITIALIZE
            END SUBROUTINE GEONWAVE_INITIALIZE
          END INTERFACE 
        END MODULE GEONWAVE_INITIALIZE__genmod
